Repository sopt-web-advanced-study/TOY-PROJECT, pull requests merged in 2023-12, with the labels that each got.

#8 [REFACTOR] 네이밍 컨벤션 및 스타일 컨벤션
  components/common/btn/categoryButtons.tsx
  components/common/btn/followButtons.tsx
  components/common/btn/selectButtons.tsx
  components/common/button.tsx
Labels: 🔧refactor, 🦖이가영

#10 [FEFACTOR] 팔로우 확인 뷰 UI 리팩토링
  .eslintrc.json
  components/checkfollow/FollowList.tsx
  components/checkfollow/FollowOrNotBtn.tsx
  components/checkfollow/Profile.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: 🔗init, 🐬이도윤, 🔧refactor

#5 [DESIGN] 팔로우 확인 뷰 UI 구현
  .eslintrc.json
  app/checkfollow/page.tsx
  components/checkfollow/FollowList.tsx
  components/checkfollow/FollowOrNotBtn.tsx
  components/checkfollow/ListElement.tsx
  components/checkfollow/Profile.tsx
  package.json
  public/next.svg
  public/santaHatImg.png
  public/vercel.svg
  tsconfig.json
  yarn.lock
Labels: 🐬이도윤, 💄design

#4 [DESIGN] CheckFollow 버튼 구현
  components/common/btn/categoryButtons.tsx
  components/common/btn/followButtons.tsx
  components/common/btn/selectButtons.tsx
Labels: 💄design, 🦖이가영

#12 [ REFACTOR ] Main Ui 코드리뷰 반영
  app/main/page.tsx
  styles/global.ts
Labels: 🐣권혜인, 🔧refactor

#9 [ DESIGN ] MAIN 뷰 UI 구현
  app/main/page.tsx
  components/main/ConfrimFollowButton.tsx
  components/main/LoginButton.tsx
  components/main/MainContainer.tsx
  components/main/TokenInput.tsx
  components/main/TokenMakeButton.tsx
  components/main/UserCheckText.tsx
  public/github_emoji.svg
  public/santahat.png
  styles/common.ts
  styles/global.ts
Labels: 🐣권혜인, 🎄etc, 💄design, 🎞assets
