Repository sopt-web-advanced-study/TOY-PROJECT, pull requests merged in 2023-12, with the labels that each got.

#3 [ design ] common style 공통으로 빼기
  toy-project/app/layout.tsx
  toy-project/app/page.tsx
  toy-project/public/santahat.png
  toy-project/styles/common.css
Labels: 🎞assets, 🐣권혜인, 💄design

#5 [DESIGN] CheckFollow UI 퍼블리싱
  toy-project/app/checkfollow/page.tsx
  toy-project/components/checkfollow/FollowList.tsx
  toy-project/components/checkfollow/FollowOrNotBtn.tsx
  toy-project/components/checkfollow/ListElement.tsx
  toy-project/components/checkfollow/Profile.tsx
  toy-project/styles/common.css
Labels: 💄design, 🐬이도윤

#8 Design#1 mainui
  toy-project/app/globals.css
  toy-project/app/page.tsx
  toy-project/components/main/ConfirmFollowButton.tsx
  toy-project/components/main/LoginButton.tsx
  toy-project/components/main/MainContainer.tsx
  toy-project/components/main/TokenInput.tsx
  toy-project/components/main/TokenMakeButton.tsx
  toy-project/components/main/UserCheckText.tsx
  toy-project/public/github_emoji.svg
  toy-project/styles/common.css
  toy-project/styles/mainpage.css
Labels: 🐣권혜인, 💄design

#10 [ FEAT ] GET API 연결 & 버튼 클릭에 따른 필터링
  toy-project/apis/getFollowList.ts
  toy-project/apis/getProfileInfo.ts
  toy-project/app/checkfollow/page.tsx
  toy-project/components/checkfollow/FollowList.tsx
  toy-project/components/checkfollow/FollowOrNotBtn.tsx
  toy-project/components/checkfollow/ListElement.tsx
  toy-project/components/checkfollow/Profile.tsx
  toy-project/components/main/ConfirmFollowButton.tsx
  toy-project/components/main/LoginButton.tsx
  toy-project/components/main/TokenInput.tsx
  toy-project/components/main/TokenMakeButton.tsx
  toy-project/next.config.js
  toy-project/package.json
  toy-project/recoil/atoms.ts
  toy-project/types/types.ts
  toy-project/yarn.lock
Labels: 🎄etc, 💡feat, 🐬이도윤

#12 [ FEAT ] PUT API 연결
  toy-project/.gitignore
  toy-project/apis/create.ts
  toy-project/apis/putFollowList.ts
  toy-project/app/checkfollow/page.tsx
  toy-project/app/layout.tsx
  toy-project/app/page.tsx
  toy-project/components/checkfollow/FollowList.tsx
  toy-project/components/checkfollow/ListElement.tsx
  toy-project/recoil/atoms.ts
  toy-project/types/types.ts
  toy-project/utils/.keep
  toy-project/utils/recoilRoot.tsx
Labels: 🐞fix, 🐣권혜인, 💡feat
